name: simple_ios_image_picker
description: simple ios image picker.
version: 0.0.2
homepage: https://corp.artisan.inc/
repository: "https://github.com/gembahub/simple_ios_image_picker"

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cross_file: ^0.3.3+4
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SimpleIosImagePickerPlugin
